name: 'Sight Words Pipeline'
resources:
- repo: self
jobs:
- job: Build
  displayName: 'Build'
  pool:
    name: 'Hosted Ubuntu 1604'
    demands: npm
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
  - script: |
      yarn install
      yarn build
    displayName: 'yarn install and build'
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: drop'